"""Transform configuration builder."""

import logging

from ai.llm import llm

from models.ddl import DDL

logger = logging.getLogger(__name__)
from models.extract import ExtractConfig
from models.load import LoadConfig
from models.transform import TransformConfig


class TransformConfigBuilder:
    """Builder for TransformConfig."""

    async def __call__(
        self, ddl: DDL, extract_config: ExtractConfig, load_config: LoadConfig, prompt: str
    ) -> TransformConfig:
        """Build TransformConfig from DDL, ExtractConfig, LoadConfig and prompt using LLM.

        Args:
            ddl: The DDL configuration.
            extract_config: The extract configuration.
            load_config: The load configuration.
            prompt: User prompt.

        Returns:
            TransformConfig generated by LLM.
        """
        structured_llm = llm.with_structured_output(TransformConfig)

        system_prompt = """
        Generate a TransformConfig for an ETL pipeline based on the provided DDL, ExtractConfig, LoadConfig, and user requirements.

        Analyze the configurations to understand:
        - Source data structure from ExtractConfig
        - Target schema from DDL and LoadConfig
        - Data types and field mappings
        - User transformation requirements

        Based on this analysis, generate:
        - Identity keys for unique entity identification
        - Transformation rules (SQL, Python functions, validations, etc.)
        - Validation rules for data quality
        - Business rules for domain logic
        - Data type mappings between source and target
        - Processing mode (batch, streaming, etc.)
        - Resource configurations

        Create meaningful transformation rules that convert source data to match the target schema.
        Include appropriate validation rules for data integrity.
        Suggest reasonable defaults for processing parameters.
        """

        user_message = f"""
        DDL: {ddl.model_dump_json()}
        ExtractConfig: {extract_config.model_dump_json()}
        LoadConfig: {load_config.model_dump_json()}
        User Prompt: {prompt}
        """

        transform_config = await structured_llm.ainvoke(
            [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_message}]
        )
        logger.debug(f"TransformConfig fields: {transform_config}")
        return transform_config
