"""Transform configuration builder."""

import logging

from ai.llm import llm

from models.ddl import DDL

logger = logging.getLogger(__name__)
from models.extract import ExtractConfig
from models.load import LoadConfig
from models.transform import TransformConfig
from models.app.update_etl import FeedbackItem


class TransformConfigBuilder:
    """Builder for TransformConfig."""

    async def __call__(
        self,
        ddl: DDL,
        extract_config: ExtractConfig,
        load_config: LoadConfig,
        prompt: str,
        old_transform_config: TransformConfig | None = None,
        feedback_items: list[FeedbackItem] | None = None,
        overall_feedback: str | None = None
    ) -> TransformConfig:
        """Build TransformConfig from DDL, ExtractConfig, LoadConfig and prompt using LLM.

        Args:
            ddl: The DDL configuration.
            extract_config: The extract configuration.
            load_config: The load configuration.
            prompt: User prompt.
            old_transform_config: Existing config to refine (optional).
            feedback_items: Specific feedback items for transform (optional).
            overall_feedback: General feedback (optional).

        Returns:
            TransformConfig generated by LLM.
        """
        structured_llm = llm.with_structured_output(TransformConfig)

        if old_transform_config:
            system_prompt = """
            Refine the existing TransformConfig for an ETL pipeline based on user feedback and new requirements.

            Start with the existing configuration and modify only what's needed based on feedback.
            Analyze the DDL, ExtractConfig, LoadConfig to understand current structure.
            Based on feedback and new prompt, update:
            - Identity keys, transformation rules, validation rules
            - Business rules, data type mappings, processing mode
            - Resource configurations

            Preserve good parts of the existing config and only change what's specifically requested in feedback.
            """
            user_message = f"""
            Existing TransformConfig: {old_transform_config.model_dump_json()}
            DDL: {ddl.model_dump_json()}
            ExtractConfig: {extract_config.model_dump_json()}
            LoadConfig: {load_config.model_dump_json()}
            User Prompt: {prompt}
            """
            if feedback_items:
                user_message += f"\nFeedback Items: {[item.model_dump() for item in feedback_items]}"
            if overall_feedback:
                user_message += f"\nOverall Feedback: {overall_feedback}"
        else:
            system_prompt = """
            Generate a TransformConfig for an ETL pipeline based on the provided DDL, ExtractConfig, LoadConfig, and user requirements.

            Analyze the configurations to understand:
            - Source data structure from ExtractConfig
            - Target schema from DDL and LoadConfig
            - Data types and field mappings
            - User transformation requirements

            Based on this analysis, generate:
            - Identity keys for unique entity identification
            - Transformation rules (SQL, Python functions, validations, etc.)
            - Validation rules for data quality
            - Business rules for domain logic
            - Data type mappings between source and target
            - Processing mode (batch, streaming, etc.)
            - Resource configurations

            Create meaningful transformation rules that convert source data to match the target schema.
            Include appropriate validation rules for data integrity.
            Suggest reasonable defaults for processing parameters.
            """

            user_message = f"""
            DDL: {ddl.model_dump_json()}
            ExtractConfig: {extract_config.model_dump_json()}
            LoadConfig: {load_config.model_dump_json()}
            User Prompt: {prompt}
            """

        transform_config = await structured_llm.ainvoke(
            [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_message}]
        )
        logger.debug(f"TransformConfig fields: {transform_config}")
        return transform_config
