include:
  - path: "docker-compose.airflow.yaml"
    env_file: ".env"

services:
  backend:
    build:
      context: .
    network_mode: host
    env_file:
      - .env
    ports:
      - ${APP_PORT:-8000}:8000
    restart: unless-stopped
