services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${APP_PORT:-8000}:8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
