include:
  - path: "docker-compose.langfuse.yaml"
    env_file: ".env"

services:
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${APP_PORT:-8000}:8000
    depends_on:
      postgres:
        condition: service_healthy
      langfuse-web:
        condition: service_started
    restart: unless-stopped
