[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiologger>=0.7.0",
    "fastapi>=0.116.2",
    "kafka-python>=2.2.15",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.33",
    "langfuse>=3.4.0",
    "pydantic-settings>=2.10.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.35.0",
    "kafka",
    "sqlalchemy", 
    "psycopg2-binary",
    "pandas"
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.0",
]

[tool.ruff]
target-version = "py312" # Target Python version
line-length = 100 # Max line length

[tool.ruff.format]
quote-style = "double" # Use double quotes for strings
indent-style = "space" # Use spaces for indentation
docstring-code-format = true # Format docstrings with code blocks

[tool.ruff.lint]
select = [
  "E", "W", "F", # Pyflakes & Pycodestyle (correctness & style)
  "I", # isort (import sorting)
  "N", # pep8-naming (snake_case/CamelCase)
  "ANN", # flake8-annotations (require type hints)
  "D", # pydocstyle (docstrings)
  "B", # flake8-bugbear (bug-prone patterns)
  "UP", # pyupgrade (modern syntax)
  "S", # flake8-bandit (basic security / secrets smells)
  "C90", # McCabe complexity
  "PD", # Pydantic-specific best practices
  "RUF" # Ruff extras (e.g., invalid noqa)
]
ignore = [
  "D212", # Multi-line summary should start at first line
  "RUF001", # Ignore checking of Cyrillic characters
  "S101", # Allow use of assert statements
]
mccabe.max-complexity = 10 # McCabe threshold

[tool.ruff.lint.pydocstyle]
convention = "google" # Enforce Google-style docstrings

[tool.ruff.lint.flake8-annotations]
suppress-dummy-args = true # Don't complain about placeholders like "_"
suppress-none-returning = true # Don't complain about functions that return None

[tool.pytest.ini_options]
pythonpath = "."
norecursedirs = ["volumes"]
