"""Load configuration builder."""

import logging

from ai.llm import llm

from models.extract import ExtractConfig

logger = logging.getLogger(__name__)
from models.load import (
    BatchConfig,
    ColumnField,
    CompressionConfig,
    FlatMetaModel,
    Index,
    IndexingConfig,
    LoadConfig,
    LoadResourceConfig,
    LoadStrategy,
    MonitoringConfig,
    NestingMetaModel,
    PartitioningConfig,
    TargetStorageTypeRecommendation,
)


class LoadConfigBuilder:
    """Builder for LoadConfig."""

    async def __call__(self, extract_config: ExtractConfig, prompt: str) -> LoadConfig:
        """Build LoadConfig from ExtractConfig and prompt using LLM.

        Args:
            extract_config: The extract configuration.
            prompt: User prompt.

        Returns:
            LoadConfig generated by LLM.
        """
        logger.info("Building LoadConfig from ExtractConfig and prompt using LLM")
        structured_llm = llm.with_structured_output(LoadConfig)

        system_prompt = """
        Generate a LoadConfig for an ETL pipeline based on the provided ExtractConfig and user requirements.

        Analyze the ExtractConfig to understand:
        - Source type and metadata
        - Content structure and fields
        - Data types and constraints

        Based on the source and user prompt, determine:
        - Target storage type (postgres, clickhouse, or hdfs) - choose based on data volume, query patterns, and user needs
        - Target connection string (use placeholder format like 'postgresql://user:pass@host:port/db' or similar)
        - Flat meta model with appropriate fields derived from extract content
        - Indexes for performance (primary keys, clustered indexes)
        - Partitioning strategy
        - Load strategy (append, upsert, etc.)
        - Other configurations (batch, compression, resources, monitoring)

        For flat_meta_model.fields, map from extract content attributes to ColumnField with proper data types.
        Suggest reasonable defaults for all configurations.
        Provide explanations for your choices.
        """

        user_message = f"""
        ExtractConfig: {extract_config.model_dump_json()}
        User Prompt: {prompt}
        """

        load_config = await structured_llm.ainvoke(
            [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_message}]
        )
        logger.info(f"LoadConfig built for target: {load_config.target_storage_type.storage_type}")
        return load_config
