"""Load configuration builder."""

import logging

from ai.llm import llm
from models.app.update_etl import FeedbackItem
from models.extract import ExtractConfig
from models.load import (
    LoadConfig,
)

logger = logging.getLogger(__name__)


class LoadConfigBuilder:
    """Builder for LoadConfig."""

    async def __call__(
        self,
        extract_config: ExtractConfig,
        prompt: str,
        old_load_config: LoadConfig | None = None,
        feedback_items: list[FeedbackItem] | None = None,
        overall_feedback: str | None = None,
    ) -> LoadConfig:
        """Build LoadConfig from ExtractConfig and prompt using LLM.

        Args:
            extract_config: The extract configuration.
            prompt: User prompt.
            old_load_config: Existing config to refine (optional).
            feedback_items: Specific feedback items for load (optional).
            overall_feedback: General feedback (optional).

        Returns:
            LoadConfig generated by LLM.
        """
        structured_llm = llm.with_structured_output(LoadConfig)

        if old_load_config:
            system_prompt = """
            Refine the existing LoadConfig for an ETL pipeline based on user feedback
            and new requirements.

            Start with the existing configuration and modify only what's needed based on feedback.
            Analyze the ExtractConfig to understand current source structure.
            Based on feedback and new prompt, update:
            - Target storage type if needed
            - Target connection string
            - Database name, schema name, and table name if needed
            - Flat meta model fields
            - Indexes, partitioning, load strategy
            - Other configurations

            IMPORTANT:
            - Ensure database_name, schema_name, and table_name are properly set
            - For PostgreSQL: schema_name should be 'public' or appropriate schema
            - For ClickHouse: schema_name should be 'default'
            - For HDFS: schema_name should be '' (empty string)

            Preserve good parts of the existing config and only change what's specifically
            requested in feedback.
            """
            user_message = f"""
            Existing LoadConfig: {old_load_config.model_dump_json()}
            ExtractConfig: {extract_config.model_dump_json()}
            User Prompt: {prompt}
            """
            if feedback_items:
                user_message += (
                    f"\nFeedback Items: {[item.model_dump() for item in feedback_items]}"
                )
            if overall_feedback:
                user_message += f"\nOverall Feedback: {overall_feedback}"
        else:
            system_prompt = """
            Generate a LoadConfig for an ETL pipeline based on the provided ExtractConfig
            and user requirements.

            Analyze the ExtractConfig to understand:
            - Source type and metadata
            - Content structure and fields
            - Data types and constraints

            Based on the source and user prompt, determine:
            - Target storage type (postgres, clickhouse, or hdfs) - choose based on data volume,
              query patterns, and user needs
            - Target connection string (use placeholder format like 'postgresql://user:pass@host:port/db'
              or similar)
            - Database name (e.g., 'analytics', 'dwh', 'data_warehouse')
            - Schema name (e.g., 'public' for PostgreSQL, 'default' for ClickHouse)
            - Table name (e.g., 'customer_orders', 'events', 'transactions')
            - Flat meta model with appropriate fields derived from extract content
            - Indexes for performance (primary keys, clustered indexes)
            - Partitioning strategy
            - Load strategy (append, upsert, etc.)
            - Other configurations (batch, compression, resources, monitoring)

            IMPORTANT:
            - database_name, schema_name, and table_name are REQUIRED fields
            - For PostgreSQL: use schema_name='public' or appropriate schema
            - For ClickHouse: use schema_name='default' (ClickHouse rarely uses schemas)
            - For HDFS: use schema_name='' (empty string)
            - Generate meaningful table names based on the data content and user prompt
            
            For flat_meta_model.fields, map from extract content attributes to ColumnField
            with proper data types.
            Suggest reasonable defaults for all configurations.
            Provide explanations for your choices.
            """

            user_message = f"""
            ExtractConfig: {extract_config.model_dump_json()}
            User Prompt: {prompt}
            """

        load_config = await structured_llm.ainvoke(
            [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ]
        )
        logger.debug(f"LoadConfig fields: {load_config}")
        return load_config
