[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:airflow-webserver]
command=airflow webserver --port 8080
user=airflow
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/airflow-webserver.err.log
stdout_logfile=/var/log/supervisor/airflow-webserver.out.log
environment=AIRFLOW__CORE__EXECUTOR="LocalExecutor",AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql://bigdata_user:bigdata_pass@postgres:5432/airflow_db",AIRFLOW__CORE__FERNET_KEY="lv9mGx11ed56ksPBhVfNSLqwTRFapSFNAjWiOEjU2As=",AIRFLOW__WEBSERVER__SECRET_KEY="your-secret-webserver-key"

[program:airflow-scheduler]
command=airflow scheduler
user=airflow
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/airflow-scheduler.err.log
stdout_logfile=/var/log/supervisor/airflow-scheduler.out.log
environment=AIRFLOW__CORE__EXECUTOR="LocalExecutor",AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql://bigdata_user:bigdata_pass@postgres:5432/airflow_db",AIRFLOW__CORE__FERNET_KEY="lv9mGx11ed56ksPBhVfNSLqwTRFapSFNAjWiOEjU2As="

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface